Tensor examples

In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-66,  -1, -38,  83,  68, -11])

In [3]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
tensor = torch.empty(2,3)
tensor

tensor([[0.0000e+00, 7.7071e-44, 1.7584e-04],
        [6.7948e+22, 6.8989e-07, 1.0490e-08]])

In [11]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [12]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [14]:
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [16]:
eye = torch.eye(4,4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [33]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
print(a)
print(empty_like)

tensor([[    140249296641424,     140249296641424,                   0],
        [                  0,                   0, 7310593858020254331]])
tensor([[    140249296641440,     140249296641440, 3616722798912352564],
        [2318265678939828276, 2478221553439042850, 7149804592159662138]])


GPU and CPU peformance

In [68]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [78]:
%%time
start_time = time.time()

# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print('elapsed time: ', elapsed_time)

elapsed time:  0.00041484832763671875
CPU times: user 556 µs, sys: 47 µs, total: 603 µs
Wall time: 499 µs


In [81]:
%%time
# CPU time only time of execution
# Test CPU performance
SIZE = 1000
cpu_rand1 = torch.rand(SIZE,SIZE)
cpu_rand2 = torch.rand(SIZE,SIZE)

start_time = time.time()
cpu_rand = cpu_rand1 @ cpu_rand2
end_time = time.time()
elapsed_time = end_time - start_time
print('elapsed time: ',elapsed_time)

elapsed time:  0.008358478546142578
CPU times: user 90.9 ms, sys: 2.18 ms, total: 93 ms
Wall time: 24.9 ms


In [80]:
%%time
# First time on gpu will be poor
gpu_rand1 = torch.rand(SIZE,SIZE).to(device)
gpu_rand2 = torch.rand(SIZE,SIZE).to(device)

start_time = time.time()
gpu_rand = gpu_rand1 @ gpu_rand2
end_time = time.time()
elapsed_time = end_time - start_time
print('elapsed time: ',elapsed_time)

elapsed time:  9.822845458984375e-05
CPU times: user 11.9 ms, sys: 16.1 ms, total: 28 ms
Wall time: 27.4 ms


In [72]:
del gpu_rand1
del gpu_rand2
del gpu_rand

In [76]:
torch.cuda.empty_cache()

In [77]:
print(torch.cuda.memory_summary())

|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |       0 B  |    1149 MB |    1386 MB |    1386 MB |
|       from large pool |       0 B  |    1149 MB |    1386 MB |    1386 MB |
|       from small pool |       0 B  |       0 MB |       0 MB |       0 MB |
|---------------------------------------------------------------------------|
| Active memory         |       0 B  |    1149 MB |    1386 MB |    1386 MB |
|       from large pool |       0 B  |    1149 MB |    1386 MB |

Working with tensor

In [84]:
# Define probabiity tensor
probabilities = torch.tensor([0.1, 0.9])
print(probabilities) # 10% or 0.1 => 0, 90% or 0.9 => 1, each probability to the index of the probability in the tensor
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([0.1000, 0.9000])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [85]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [86]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [88]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [93]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [94]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [97]:
tensor = torch.zeros(2,3,4)
print(tensor.shape)
out = tensor.transpose(0,2)
out.shape

torch.Size([2, 3, 4])


torch.Size([4, 3, 2])

In [98]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# Stack the tensors along
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [100]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear)
print(linear(sample))

Linear(in_features=3, out_features=3, bias=False)
tensor([-10.7055,  -3.1374,   4.6692], grad_fn=<SqueezeBackward3>)


In [101]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1,dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])