Tensor examples

In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-66,  -1, -38,  83,  68, -11])

In [3]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
tensor = torch.empty(2,3)
tensor

tensor([[0.0000e+00, 7.7071e-44, 1.7584e-04],
        [6.7948e+22, 6.8989e-07, 1.0490e-08]])

In [11]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [12]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [14]:
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [16]:
eye = torch.eye(4,4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [33]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
print(a)
print(empty_like)

tensor([[    140249296641424,     140249296641424,                   0],
        [                  0,                   0, 7310593858020254331]])
tensor([[    140249296641440,     140249296641440, 3616722798912352564],
        [2318265678939828276, 2478221553439042850, 7149804592159662138]])


GPU and CPU peformance

In [34]:
import torch
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [35]:
start_time = time.time()

# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print('elapsed time: ', elapsed_time)

elapsed time:  8.344650268554688e-05
